region        = "us-east-2"
# ami           = "ami-00eb69d236edcfaf8"
# instance_type = "t2.micro"
# instance-name = "Vishal-test-app"
# instance-name2 = "Vishal-test-db"
# app = "stackstorm"
# app2 = "stackstorm-db"
