name: Install Redis on Tagged Ubuntu Hosts

on:
  workflow_dispatch:

jobs:
  ansible-install-redis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Download tfstate file from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp s3://terraform-statefile-2710/development/backend.tf terraform.tfstate --region us-east-2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore
          sudo apt-get install -y jq

      - name: Parse hostnames from tfstate file with tag "redis"
        id: parse_hosts
        run: |
          export HOSTNAMES=$(jq -r '.resources[] | select(.type == "aws_instance") | .instances[] | select(.attributes.tags.Name == "redis") | .attributes.public_dns' terraform.tfstate)
          HOSTNAMES=$(echo "$HOSTNAMES" | tr '\n' ',')
          HOSTNAMES=${HOSTNAMES%,}  # Remove trailing comma
          echo "Filtered Hostnames with tag 'redis': $HOSTNAMES"
          echo "hosts=$HOSTNAMES" >> $GITHUB_ENV

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa  # Save and remove any line endings
          chmod 600 ~/.ssh/id_rsa
          for host in $(echo "${{ env.hosts }}" | tr ',' '\n'); do
            ssh-keyscan -H "$host" >> ~/.ssh/known_hosts  # Add hosts to known_hosts
          done

      - name: Create Ansible inventory
        run: |
          echo "[redis_hosts]" > inventory.ini
          for host in $(echo "${{ env.hosts }}" | tr ',' ' '); do
            echo "$host ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
          done

      - name: Run Ansible Playbook to install Redis
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini install_redis.yml

      - name: Cleanup
        run: |
          rm -f inventory.ini terraform.tfstate ~/.ssh/id_rsa
